Repository xability/maidr, pull requests merged in 2025-06, with the labels that each got.

#303 chore: fix lint issues and errors on CodeQL workflow and config
  .github/codeql/codeql-config.yml
  .github/workflows/codeql.yml
Labels: devops

#299 fix: integrate volume toggle with audioservice
  src/controller.ts
  src/service/audio.ts
  src/service/settings.ts
Labels: bug

#297 fix: integrate prompt level into chat flow
  src/service/chat.ts
  src/service/prompts.ts
  src/type/llm.ts
  src/ui/pages/Settings.tsx
Labels: bug

#287 fix: validate llm agent api key
  src/service/llmValidation.ts
  src/ui/pages/Settings.tsx
Labels: bug, enhancement

#313 fix: implement observer on settings for audio and autoplay services
  src/controller.ts
  src/service/audio.ts
  src/service/autoplay.ts
  src/service/settings.ts
Labels: bug

#317 fix: address visual highlighting on multi lineplot
  src/model/line.ts
Labels: bug

#318 fix: adapt highlight color for heatmap cell based on cell color
  src/util/constant.ts
  src/util/svg.ts
Labels: bug

#337 fix: organize tooltip styling
  src/ui/css/styles.css
Labels: bug

#341 chore: suppress non-fatal build warnings
  vite.config.ts
Labels: devops

#343 feat: support highlight on candlestick
  examples/candlestick-vertical.html
  src/model/candlestick.ts
Labels: enhancement

#352 test: integrate unit tests for dodged barplot
  test/model/dodgedBarplot.test.ts
Labels: testing

#357 feat: address multi-panel plot highlight
  examples/multi-panel.html
  src/controller.ts
  src/model/plot.ts
  src/service/highlight.ts
  src/type/state.ts
  src/ui/css/styles.css
  src/util/svg.ts
Labels: bug

#326 feat: integrate custom prompting and chat suggestions
  eslint.config.ts
  src/service/prompts.ts
  src/state/viewModel/chatViewModel.ts
  src/type/chat.ts
  src/type/settings.ts
  src/ui/components/Suggestions.tsx
  src/ui/pages/Chat.tsx
  src/ui/pages/Settings.tsx
Labels: enhancement
