Repository xability/maidr, pull requests merged in 2025-05, with the labels that each got.

#244 feat: add instruction message tooltip on plot hover
  src/service/display.ts
  src/ui/css/styles.css
Labels: enhancement

#251 fix: implementation of missing handler methods and cleanup of event l…
  src/service/display.ts
Labels: bug

#256 feat: improvise prompts and refactor chat service
  src/service/chat.ts
  src/service/prompts.ts
Labels: enhancement

#259 build: migrate bundling from webpack to vite
  package-lock.json
  package.json
  vite.config.ts
  webpack.config.ts
Labels: devops

#229 test: integrate multi layer unit tests and add jest dependancy
  package-lock.json
  package.json
  test/model/multiLayer.test.ts
Labels: testing

#262 fix: modify filename of vite bundle post build
  vite.config.ts
Labels: bug

#263 build: patch esbuild vulnerability on vite
  package-lock.json
  package.json
Labels: devops

#161 test: integrate e2e testing framework using Playwright
  .github/workflows/check-examples.yml
  .github/workflows/e2e_tests.yml
  .gitignore
  .vscode/mcp.json
  E2E_TESTING.md
  e2e_tests/config/test-config.ts
  e2e_tests/page-objects/base-page.ts
  e2e_tests/page-objects/plots/barplot-page.ts
  e2e_tests/page-objects/plots/boxplotHorizontal-page.ts
  e2e_tests/page-objects/plots/boxplotVertical-page.ts
  e2e_tests/page-objects/plots/dodgedBarplot-page.ts
  e2e_tests/page-objects/plots/heatmap-page.ts
  e2e_tests/page-objects/plots/histogram-page.ts
  e2e_tests/page-objects/plots/lineplot-page.ts
  e2e_tests/page-objects/plots/multiLayer-page.ts
  e2e_tests/page-objects/plots/multiLineplot-page.ts
  e2e_tests/page-objects/plots/stackedBarplot-page.ts
  e2e_tests/specs/barplot.spec.ts
  e2e_tests/specs/boxplotHorizontal.spec.ts
  e2e_tests/specs/boxplotVertical.spec.ts
  e2e_tests/specs/dodgedBarplot.spec.ts
  e2e_tests/specs/heatmap.spec.ts
  e2e_tests/specs/histogram.spec.ts
  e2e_tests/specs/lineplot.spec.ts
  e2e_tests/specs/multiLayer.spec.ts
  e2e_tests/specs/multiLineplot.spec.ts
  e2e_tests/specs/stackedBarplot.spec.ts
  e2e_tests/utils/constants.ts
  e2e_tests/utils/errors.ts
  eslint.config.ts
  examples/boxplot-horizontal.html
  examples/boxplot-vertical.html
  package-lock.json
  package.json
Labels: testing

#265 chore: remove cypress related directories and references
  .gitignore
  CONTRIBUTING.md
  cypress.config.ts
  cypress/cypress.d.ts
  cypress/e2e/plot/test_barplot.cy.ts
  cypress/e2e/plot/test_heatmap.cy.ts
  cypress/e2e/plot/test_histogram.cy.ts
  cypress/e2e/plot/test_lineplot.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/tsconfig.json
  cypress/util/constant.ts
  cypress/util/helper.ts
  jest.config.ts
  package-lock.json
  package.json
Labels: testing

#267 fix: address e2e test failures
  e2e_tests/page-objects/base-page.ts
  e2e_tests/page-objects/plots/barplot-page.ts
  e2e_tests/page-objects/plots/boxplotHorizontal-page.ts
  e2e_tests/page-objects/plots/boxplotVertical-page.ts
  e2e_tests/page-objects/plots/dodgedBarplot-page.ts
  e2e_tests/page-objects/plots/heatmap-page.ts
  e2e_tests/page-objects/plots/histogram-page.ts
  e2e_tests/page-objects/plots/lineplot-page.ts
  e2e_tests/page-objects/plots/multiLayer-page.ts
  e2e_tests/page-objects/plots/multiLineplot-page.ts
  e2e_tests/page-objects/plots/stackedBarplot-page.ts
  e2e_tests/specs/boxplotHorizontal.spec.ts
  e2e_tests/specs/boxplotVertical.spec.ts
  e2e_tests/specs/dodgedBarplot.spec.ts
  e2e_tests/specs/multiLayer.spec.ts
  e2e_tests/specs/stackedBarplot.spec.ts
  e2e_tests/utils/constants.ts
Labels: testing

#272 chore: expand changes scrutiny to fix potential test failures
  .github/workflows/check-examples.yml
  .github/workflows/validate-changes.yml
Labels: devops

#270 test: add unit tests for stacked barplot
  test/model/stackedBarplot.test.ts
Labels: testing

#275 chore: address failure in e2e tests workflow
  .github/workflows/e2e_tests.yml
Labels: devops

#257 feat: enable markdown rendering for LLM agent messages
  package-lock.json
  package.json
  src/types/rehype-mathjax.d.ts
  src/ui/components/MessageBubble.tsx
  src/ui/components/TypingEffect.tsx
  src/ui/css/styles.css
  src/ui/pages/Chat.tsx
Labels: enhancement

#293 chore: clean up package lock and use npm install
  .github/workflows/release.yml
Labels: devops
